name: Build and Sign Installer

on:
  push:
    tags:
      - 'v*'  # Ex: v1.0.0

jobs:
  build-sign:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller main.spec

      - name: Compile installer with Inno Setup
        run: |
          iscc installer.iss
        shell: cmd

      - name: Upload unsigned installer artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/Setup_MSFS_State_Modifier.exe

      - name: Submit to SignPath for signing
        id: signpath-sign
        uses: SignPath/github-actions/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '762618d2-1286-4a19-9708-36a62ba19a95'
          project-slug: 'msfsstatemodifier'
          signing-policy-slug: 'flightsim.to'
          github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'signed-output'
